<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <script type="text/javascript" src="rsvp-latest.min.js" ></script>
    <script type="text/javascript">
        var getJSON = function(url) {
          var promise = new RSVP.Promise(function(resolve, reject){
            var client = new XMLHttpRequest();
            client.open("GET", url);
            client.onreadystatechange = handler;
            client.responseType = "json";
            client.setRequestHeader("Accept", "application/json");
            client.send();

            function handler() {
              if (this.readyState === this.DONE) {
                if (this.status === 200) { 
                    resolve(this.response); 
                }else {
                    reject(this.status);
                }
              }
            };
          });

          return promise;
        };

        var promise_success = getJSON('data.json');
        var promise_fail = getJSON('404.json')

        RSVP.on('error', function(e){
            console.log(e);
        });

        promise_success.then(function(data){
            return data;
        }).catch(function(data){
            console.log('promise_success catch: '+data+' no any catch exec after this catch');
        }).finally(function(data){
            console.log('promise_success finally: '+data);
        });

        promise_success.then(function(data){
            return data;
        }).catch(function(data){
            console.log('promise_success chain catch : '+data); //no exec
        }).then(function(data){
            console.log('promise_success chain then resolve: '+data.user); //user
        }).then(function(data){
            console.log('promise_success chain then resolve: '+data); //undefined
        }).catch(function(data){
            console.log('promise_success chain catch : '+data); //no exec
        });
        

        promise_fail.then(function(data){
            console.log('promise_fail success handler : '+data); //no exec
            return '404 not found'; //no exec
        }, function(reason){
            console.log('promise_fail fail handler : '+data); //no exec
        }).finally(function(){
            console.log(data);   //no exec
        }).then(function(data){
            console.log('promise_fail success chain catch : '+data); //no exec
        }).catch(function(reason){
            console.log('promise_fail chain catch : '+data); //no exec
        }).finally(function(data){
            console.log('promise_fail finally: '+data); //exec
        })
    </script>
</body>
</html>